---
- hosts: '{{ inventory }}'
  become: True
  become_user: root
  gather_facts: yes
  vars:
    ansible_ssh_user: ec2-user
    users:
    - username: "st"
      groups: "adm,wheel"
      comment: "Stephen Tse"
    - username: "lc"
      groups: "adm,wheel"
      comment: "Leo Chen"
    - username: "rj"
      groups: "adm,wheel"
      comment: "Rongjian Lan"
    - username: "md"
      groups: "adm,wheel"
      comment: "Minh Doan"
    - username: "ea"
      groups: "adm,wheel"
      comment: "Edgar Aroutiounian"
    - username: "dm"
      groups: "adm,wheel"
      comment: "Daniel Van Der Maden"
    - username: "aw"
      groups: "adm,wheel"
      comment: "Andy Wu"
    - username: "gu"
      groups: "adm,wheel"
      comment: "Ganesha Upadhyaya"
    - username: "yc"
      groups: "adm,wheel"
      comment: "Yishuang Chen"
    - username: "hb"
      groups: "adm,wheel"
      comment: "Xuan Huang"
    - username: "jl"
      groups: "adm,wheel"
      comment: "Janet Liang"
    - username: "jz"
      groups: "adm,wheel"
      comment: "Jian Zhen"
    - username: "jw"
      groups: "adm,wheel"
      comment: "John Whitton"
    - username: "sj"
      groups: "adm,wheel"
      comment: "Sebastian Johnsson"
    - username: "lw"
      groups: "adm,wheel"
      comment: "Lei Wang"
    - username: "dw"
      groups: "adm,wheel"
      comment: "Dennis Won"
    - username: "as"
      groups: "adm,wheel"
      comment: "Andrew Song"
    - username: "cf"
      groups: "adm,wheel"
      comment: "Cem Fahliogullari"
    - username: "sd"
      groups: "adm,wheel"
      comment: "Sahil Dewan"
    - username: "hd"
      groups: "adm,wheel"
      comment: "Haodi Jiang"
    - username: "lj"
      groups: "adm,wheel"
      comment: "Jiang Li"
    - username: "nw"
      groups: "adm,wheel"
      comment: "Nick White"
    - username: "ns"
      groups: "adm,wheel"
      comment: "Niteesh Settypalli"
    remove_users:
    - "foo"
  tasks:
  - name: "Create user accounts"
    user:
      name: "{{ item.username }}"
      groups: "{{ item.groups }}"
      create_home: yes
      state: "present"
    with_items: "{{ users }}"
  - name: "Remove old user accounts in remove_users"
    user:
      name: "{{ item }}"
      state: "absent"
    with_items: "{{ remove_users }}"
  - name: "Add authorized keys"
    authorized_key:
      user: "{{ item.username }}"
      key: "{{ lookup('file', '../vars/'+ item.username + '.key.pub') }}"
    with_items: "{{ users }}"
#  - name: "Allow admin users to sudo without a password"
#    lineinfile:
#      dest: "/etc/sudoers" # path: in version 2.3
#      state: "present"
#      regexp: "^%admin"
#      line: "%admin ALL=(ALL) NOPASSWD: ALL"
